name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Python dependencies
      run: |
        cd python
        python -m venv venv
        venv\Scripts\activate
        pip install -r requirements.txt
        cd ..
        
    - name: Verify shape predictor file exists
      run: |
        if (!(Test-Path "electron/assets/models/shape_predictor_68_face_landmarks.dat")) {
          Write-Error "Shape predictor file not found!"
          exit 1
        }
        Write-Host "Shape predictor file found successfully"
        
    - name: Build application
      run: npm run build
      env:
        CI: true
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: screenblink-windows
        path: |
          dist/
          dist-electron/
        retention-days: 30
        
    - name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        name: screenblink-installer
        path: |
          dist/*.exe
          dist/*.zip
        retention-days: 30 