name: Daily Download Report

on:
  schedule:
    - cron: '0 17 * * *' # 1pm EDT (change to 18 for EST in winter)
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Get all release asset download counts
        id: get_downloads
        run: |
          REPO="${{ github.repository }}"
          
          # Get all releases and calculate totals using jq
          RELEASES=$(curl -s -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$REPO/releases)
          
          # Calculate total DMG downloads across all releases
          TOTAL_DMG=$(echo "$RELEASES" | jq -r '[.[].assets[]? | select(.name | endswith(".dmg")) | .download_count // 0] | add // 0')
          
          # Calculate total EXE downloads across all releases
          TOTAL_EXE=$(echo "$RELEASES" | jq -r '[.[].assets[]? | select(.name | endswith(".exe")) | .download_count // 0] | add // 0')
          
          # Calculate total
          TOTAL_ALL=$((TOTAL_DMG + TOTAL_EXE))
          
          echo "TOTAL_DMG=$TOTAL_DMG" >> $GITHUB_ENV
          echo "TOTAL_EXE=$TOTAL_EXE" >> $GITHUB_ENV
          echo "TOTAL_ALL=$TOTAL_ALL" >> $GITHUB_ENV

      - name: Send email with total download counts
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "📊 Total Download Statistics - All Releases"
          to: katunjieli@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
            📊 Total Download Statistics - All Releases

            - macOS (.dmg) ............... ${{ env.TOTAL_DMG }}
            - Windows (.exe) ............. ${{ env.TOTAL_EXE }}

            📈 Total Downloads: ${{ env.TOTAL_ALL }}

            ---
            This represents the cumulative download count across all releases.